common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),

]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mysite/", include("mysite.urls")),
    path("", include("pages.urls"))
]

mysite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.company_productList),
    path("productLine<str:productLineNumber>/", views.company_productLine),
    path("<str:product_name>/", views.detail),
    path('comment/create/<str:product_name>/', views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),

]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.mainpage),
    path("company-introduce/", views.company_introduce),
    path("company-history/", views.company_history),
    path("company-info/", views.company_info),

]

common/models.py
from django.db import models

# Create your models here.

mysite/models.py
from django.db import models
from django.contrib.auth.models import User

class MainContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField("date published")

class Product(models.Model):
    name = models.CharField(max_length=100)
    productLine = models.CharField(max_length=20)
    price = models.IntegerField(default=0)
    description = models.TextField()
    pub_date = models.DateTimeField("date published")
    image = models.ImageField(upload_to='products/', blank=True)
    def __str__(self):
        return self.name

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content_list = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

pages/models.py
from django.db import models

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

mysite/forms.py
from .models import Comment
from django import forms
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

common/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import logout, authenticate, login
from common.forms import UserForm

def logout_view(request):
    logout(request)
    return redirect('/')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

mysite/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import  get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import Product, Comment
from .forms import CommentForm

# def company_productList(request):
#     content_list = MainContent.objects.order_by("-pub_date")
#     context = {"content_list": content_list}
#     return render(request, "mysite/productList.html", context)

def company_productList(request):
    productList = Product.objects.order_by("-pub_date")
    dataSet = {"productList": productList}
    return render(request, "mysite/productList.html", dataSet)

def company_productLine(request, productLineNumber):
    productList = Product.objects.filter(productLine=productLineNumber).order_by("-pub_date")
    dataSet = {"productList": productList}
    return render(request, "mysite/productLine.html", dataSet)

def detail(request, product_name):
    productList = Product.objects.get(name=product_name)
    dataSet = {'productList': productList}
    return render(request, 'mysite/detail.html', dataSet)

@login_required(login_url='common:login')
def comment_create(request, product_name):
    # productList = get_object_or_404(Product, pk=product_name)
    productList = Product.objects.get(name=product_name)
    if request.method == 'POST':
        form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.content_list = productList
        comment.author = request.user
        comment.save()
        # return redirect('detail', content_id=productList.name)
        return render(request, 'mysite/detail.html', {'productList': productList})
    else:
        form = CommentForm()
        context = {'productList': productList, 'form': form}
        return render(request, 'mysite/detail.html', context)

@login_required(login_url='common:login')
def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    productList = Product.objects.get(name=comment.content_list)
    if request.user != comment.author:
        raise PermissionDenied
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            # return redirect('detail', content_id=comment.content_list.id)
            return render(request, 'mysite/detail.html', {'productList': productList})
    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'mysite/comment_form.html', context)

@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    productList = Product.objects.get(name=comment.content_list)
    if request.user != comment.author:
        raise PermissionDenied
    else:
        comment.delete()
    # return redirect('detail', content_id=comment.content_list.id)
    return render(request, 'mysite/detail.html', {'productList': productList})

pages/views.py
from django.shortcuts import render

def mainpage(request):
    return render(request, 'pages/mainpage.html')

def company_introduce(request):
    return render(request, 'pages/company_introduce.html')

def company_history(request):
    return render(request, 'pages/company_history.html')

def company_info(request):
    return render(request, 'pages/company_info.html')

def login_page(request):
    return render(request, 'pages/login.html')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Small Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    </head>
    <body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    <div id="quickNavigator">
        {% if user.is_authenticated %}
        <div>마이페이지</div>
        <div>안녕하세요 {{ user.username }}님!</div>
        <div class="quickNavigator-submenu">
            <div><a href="/profile">프로필</a></div>
            <div><a href="/settings">설정</a></div>
            <div><a href="/messages">메시지</a></div>
        </div>
        {% else %}
        <div>마이페이지</div>
        <div>로그인이 필요합니다.</div>
        {% endif %}
    </div>
    {% include "footer.html" %}
    </body>
</html>

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<img class="main-image" src="../../static/backgroundimage.png" alt="Main Image">
<div id="login-field">
    <div class="container my-3">
        <form method="post" action="{% url 'common:login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">ID</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password">PASSWORD</label>
                <input type="password" class="form-control" name="password" id="password"
                       value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">로그인</button>
        </form>
    </div>
</div>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<img class="main-image" src="../../static/backgroundimage.png" alt="Main Image">
<div id="signup-field">
    <div class="container my-3">
        <form method="post" action="{% url 'common:signup' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">ID</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password1">PASSWORD</label>
                <input type="password" class="form-control" name="password1" id="password1"
                       value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password2">PASSWORD CHECK</label>
                <input type="password" class="form-control" name="password2" id="password2"
                       value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="email">E-MAIL</label>
                <input type="text" class="form-control" name="email" id="email"
                       value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">회원가입</button>
        </form>
    </div>
</div>
{% endblock %}

templates/footer.html
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
</footer>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/mysite/comment_form.html
{% extends 'base.html' %}
{% block content %}
<h2> update comment</h2>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_update' comment.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3">{{ form.content.value }}</textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/mysite/detail.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ productList.name }}</h2>
<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="col-lg-7">
        {% with default_image_url="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" %}
            <img class="img-fluid rounded mb-4 mb-lg-0" id="Product_Image_{{ product.name }}"
                 src="{% if productList.image %}{{ productList.image.url }}{% else %}{{ default_image_url }}{% endif %}"
                 alt="Product Image" />
        {% endwith %}
    </div>
    <div>
    {{ productList.description }}
    </div>
</div>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_create' productList.name %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3"
                placeholder="내용을 입력해주세요."></textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        {% for comment in productList.comment_set.all %}
        <div class="d-flex">
            <div class="ms-3">
                <div class="fw-bold">{{ comment.author.username }} &nbsp&nbsp{{ comment.create_date }}
                {% if comment.create_date != comment.modify_date %}
                / 수정일자: {{ comment.modify_date }}
                {% endif %}
                {% if request.user == comment.author %}
                <a href="{% url 'comment_update' comment.id %}" class="btn btn-sm btn-outlinesecondary">수정</a>
                <a href="{% url 'comment_delete' comment.id %}" class="btn btn-sm btn-outlinesecondary">삭제</a>
                {% endif %}
                </div>
                {{ comment.content }}
            </div>
        </div>
        <br/>
        {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

templates/mysite/productLine.html
{% extends 'base.html' %}
{% block content %}
<div class="container px-4 px-lg-5">
{% if productList %}
    {% for product in productList %}
        <div class="row gx-4 gx-lg-5 align-items-center my-5">
            <div class="col-lg-7">
                {% with default_image_url="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" %}
                    <img class="img-fluid rounded mb-4 mb-lg-0" id="Product_Image_{{ product.name }}"
                         src="{% if product.image %}{{ product.image.url }}{% else %}{{ default_image_url }}{% endif %}"
                         alt="Product Image" />
                {% endwith %}
            </div>
            <div class="col-lg-5">
                <h1 class="font-weight-light">{{ product.name }}</h1>
                <p>{{ product.description }}</p>
                <a class="btn btn-primary" href="../{{ product.name }}">상품 상세보기</a>
            </div>
        </div>
        <script>
        document.getElementById("Product_Image_{{ product.name }}").onclick = function() {
            window.location.href = "../{{ product.name }}";
        };
        </script>
    {% endfor %}
{% else %}
    <p>content가 없습니다.</p>
{% endif %}
</div>
{% endblock %}

templates/mysite/productLine1.html
{% extends 'base.html' %}
{% block content %}
<div class="container px-4 px-lg-5">
{% if productList %}
    {% for product in productList %}
        {% if product.productLine == '1' %}
        <div class="row gx-4 gx-lg-5 align-items-center my-5">
            <div class="col-lg-7">
                {% with default_image_url="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" %}
                    <img class="img-fluid rounded mb-4 mb-lg-0" id="Product_Image_{{ product.name }}"
                         src="{% if product.image %}{{ product.image.url }}{% else %}{{ default_image_url }}{% endif %}"
                         alt="Product Image" />
                {% endwith %}
            </div>
            <div class="col-lg-5">
                <h1 class="font-weight-light">{{ product.name }}</h1>
                <p>{{ product.description }}</p>
                <a class="btn btn-primary" href="../{{ product.name }}">상품 상세보기</a>
            </div>
        </div>
        <script>
        document.getElementById("Product_Image_{{ product.name }}").onclick = function() {
            window.location.href = "../{{ product.name }}";
        };
        </script>
        {% endif %}
    {% endfor %}
{% else %}
    <p>content가 없습니다.</p>
{% endif %}
</div>
{% endblock %}

templates/mysite/productList.html
{% extends 'base.html' %}
{% block content %}
<div class="container px-4 px-lg-5">
{% if productList %}
    {% for product in productList %}
        <div class="row gx-4 gx-lg-5 align-items-center my-5">
            <div class="col-lg-7">
                {% with default_image_url="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" %}
                    <img class="img-fluid rounded mb-4 mb-lg-0" id="Product_Image_{{ product.name }}"
                         src="{% if product.image %}{{ product.image.url }}{% else %}{{ default_image_url }}{% endif %}"
                         alt="Product Image" />
                {% endwith %}
            </div>
            <div class="col-lg-5">
                <h1 class="font-weight-light">{{ product.name }}</h1>
                <p>{{ product.description | truncatewords:30 }}</p>
                <a class="btn btn-primary" href="{{ product.name }}">상품 상세보기</a>
            </div>
        </div>
        <script>
        document.getElementById("Product_Image_{{ product.name }}").onclick = function() {
            window.location.href = "{{ product.name }}";
        };
        </script>
    {% endfor %}
{% else %}
    <p>등록된 상품이 없습니다.</p>
{% endif %}
</div>
{% endblock %}

templates/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="height : 80px">
    <div class="container px-5">
        <a class="navbar-brand" href="/" style="font-size : 24px">회사명</a>
        <span style="width : 5%;"></span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <span style="width : 5%;"></span>
            <table style="line-height: 80px;">
                <tr>
                    <td width="200"><a class="nav-link active" id="introduce-nav" aria-current="page" href="/company-introduce" style="text-align:center">회사</a></td>
                    <td width="200"><a class="nav-link" id="product-nav" href="/product" style="text-align:center">제품</a></td>
                    <td width="200"><a class="nav-link" id="PR-nav" href="/PR-videos" style="text-align:center">홍보</a></td>
                    <td width="200"><a class="nav-link" id="service-nav" href="/service" style="text-align:center">고객센터</a></td>
                </tr>
            </table>
        </div>

        <div id="submenu">
            <div id="companyMenu">
                <table>
                    <tr>
                        <td><a href="/company-introduce">회사소개</a></td>
                        <td><a href="/company-history">회사연혁</a></td>
                        <td><a href="/company-info">회사정보</a></td>
                    </tr>
                </table>
            </div>
            <div id="productMenu">
                <table>
                    <tr>
                        <td><a href="/product/productLine1">제품군 1</a></td>
                        <td><a href="/product/productLine2">제품군 2</a></td>
                        <td><a href="/product/productLine3">제품군 3</a></td>
                        <td><a href="/product/productLine4">제품군 4</a></td>
                    </tr>
                </table>
            </div>
            <div id="PRMenu">
                <table>
                    <tr>
                        <td><a href="/PR-videos">영상</a></td>
                        <td><a href="/SNS">SNS</a></td>
                    </tr>
                </table>
            </div>
            <div id="serviceMenu">
                <table>
                    <tr>
                        <td><a href="/FAQ">FAQ</a></td>
                        <td><a href="/1to1">1:1문의</a></td>
                    </tr>
                </table>
            </div>
        </div>


        <div id="login-section">
            {% if user.is_authenticated %}
            <a class="nav-link btn btn-outline-light" href="{% url 'common:logout' %}" style="width:100px;">로그아웃</a>
            {% else %}
            <a href="{% url 'common:login' %}" class="btn btn-outline-light" style="width:80px;">로그인</a>
            {% endif %}
        </div>

        <div id="signup-section" style="margin:10px;">
            {% if not user.is_authenticated %}
            <a class="nav-link btn btn-outline-light" href="{% url 'common:signup' %}" style="width:100px; height:38px;">회원가입</a>
            {% endif %}
        </div>

    </div>
</nav>
<script>
    // 메뉴를 숨기는 함수
    function hideAllMenus() {
        document.getElementById("companyMenu").style.display = "none";
        document.getElementById("productMenu").style.display = "none";
        document.getElementById("PRMenu").style.display = "none";
        document.getElementById("serviceMenu").style.display = "none";
    }

    // 각 메뉴에 이벤트를 추가하여 숨겨진 메뉴를 보여줌
    document.getElementById("introduce-nav").addEventListener("mouseover", function () {
        document.getElementById("submenu").style.display = "block";
        hideAllMenus();
        document.getElementById("companyMenu").style.display = "block";
    });
    document.getElementById("companyMenu").addEventListener("mouseover", function () {
        document.getElementById("submenu").style.display = "block";
        hideAllMenus();
        document.getElementById("companyMenu").style.display = "block";
    });

    document.getElementById("product-nav").addEventListener("mouseover", function () {
        document.getElementById("submenu").style.display = "block";
        hideAllMenus();
        document.getElementById("productMenu").style.display = "block";
    });
    document.getElementById("productMenu").addEventListener("mouseover", function () {
        document.getElementById("submenu").style.display = "block";
        hideAllMenus();
        document.getElementById("productMenu").style.display = "block";
    });

    document.getElementById("PR-nav").addEventListener("mouseover", function () {
        document.getElementById("submenu").style.display = "block";
        hideAllMenus();
        document.getElementById("PRMenu").style.display = "block";
    });
    document.getElementById("PRMenu").addEventListener("mouseover", function () {
        document.getElementById("submenu").style.display = "block";
        hideAllMenus();
        document.getElementById("PRMenu").style.display = "block";
    });

    document.getElementById("service-nav").addEventListener("mouseover", function () {
        document.getElementById("submenu").style.display = "block";
        hideAllMenus();
        document.getElementById("serviceMenu").style.display = "block";
    });
    document.getElementById("serviceMenu").addEventListener("mouseover", function () {
        document.getElementById("submenu").style.display = "block";
        hideAllMenus();
        document.getElementById("serviceMenu").style.display = "block";
    });

    document.getElementById("navbarSupportedContent").addEventListener("mouseout", function () {
        hideAllMenus();
        document.getElementById("submenu").style.display = "none";
    });
</script>

templates/pages/company_history.html
{% extends 'base.html' %}
{% block content %}
<img class="main-image" src="../../static/backgroundimage.png" alt="Main Image">
<div id="history-bar">
    <div class="m-0 text-white" style="font-size: 40px;">2020</div>
    <br>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
</div>
{% endblock %}

templates/pages/company_info.html
{% extends 'base.html' %}
{% block content %}
<img class="main-image" src="../../static/backgroundimage.png" alt="Main Image">
<div id="information-bar">
    <div class="m-0 text-white" style="font-size: 40px;">찾아오는 길</div>
    <br>
    <div class="m-0 text-white">주저리 주저리</div>
    <img class="Map-image" src="../../static/roadmap.jpg" alt="Map Image" style="width:80%; height:80%; top:50%;">

</div>
<div>옵션</div>
<p>옵션</p>
{% endblock %}

templates/pages/company_introduce.html
{% extends 'base.html' %}
{% block content %}
<img class="main-image" src="../../static/backgroundimage.png" alt="Main Image">
<div id="introduce-bar">
    <div class="m-0 text-white">우리는 이렇게 일합니다.</div>
    <br>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
</div>
{% endblock %}

templates/pages/mainpage.html
{% extends 'base.html' %}
{% block content %}
<img class="main-image" src="../../static/backgroundimage.png" alt="Main Image">
<div class="slogan-bar">
    <div class="m-0 text-white">회사의 슬로건</div>
    <br>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
    <div class="m-0 text-white">주저리 주저리</div>
</div>
{% endblock %}